services:
  project1:
    build: ./
    
    container_name: webscraper
    ports:
      - 8080:8080"  # host:container
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    mem_limit: 400m
    restart: always